const IMAGES = {
  congrats: require('../assets/congratulation.png'),
  googgleLogo: require('../assets/download-removebg-preview.png'),
  firstPage: require('../assets/Firstpage.png'),
  splashLogo: require('../assets/image-removebg-preview.png'),
  signupInLogo: require('../assets/Second.png'),
  profile : require('./profile.jpg'),
  home: require('./Home.png'),
  general: require('./General.png'),
  dentist: require('./Dentist.png'),
  ophithal: require('./ophithal.png'),
  nutrition: require('./Nutrition.png'),
  neurologist: require('./Neurologist.png'),
  pediatric: require('./Pediatric.png'),
  radiologic: require('./Radiologic.png'),
  more: require('./More.png'),
  cancelled: require('./NotificationCancelled.png'),
  scheduleChange: require('./download.png'),
  appointSuccess: require('./download1.png'),
  newServiceAvail: require('./download2.png'),
  cardConnect: require('./download3.png'),
  travis: require('./travis.png'),
  jenny: require('./image.png'),
  raul: require('./image1.png'),
  elijah: require('./image2.png'),
  randy: require('./image3.png')
};
export default IMAGES;
